EN_US = 'EN-US'
FR_FR = 'FR-FR'

LOCALIZATIONS = [
    {
        'local':'EN-US',
        # LOCALS
        'EN-US':'English',
        'FR-FR':'Français',
        # COMMANDS
        # Missing arguments
        'missing_arg':'Missing arguments. Check %help for more informations.',
        # Local
        'local_success':'Bot new local set to ',
        'local_fail':'Could not find local ',
        # Have
        'have_success':'Characters with ',
        'have_fail':'No Character seems to interact with ',
        # Ability Classes
        'Ability Block':'Ability Block',
        'Accuracy Down':'Accuracy Down',
        'Accuracy Up':'Accuracy Up',
        'Advantage':'Advantage',
        'AoE':'AoE',
        'Armor Shred':'Armor Shred',
        'Assist':'Assist',
        'Blind':'Blind',
        'Bonus Attack':'Bonus Attack',
        'Bonus Turn':'Bonus Turn',
        'Breach':'Breach',
        'Buff Immunity':'Buff Immunity',
        'Buff Steal':'Buff Steal',
        'Burning':'Burning',
        'CD Increase':'CD Increase',
        'CD Reduction':'CD Reduction',
        'CD Reset':'CD Reset',
        'Cleanse':'Cleanse',
        'Confuse':'Confuse',
        'Counter':'Counter',
        'Crit Chance Down':'Crit Chance Down',
        'Crit Chance Up':'Crit Chance Up',
        'Crit Damage Down':'Crit Damage Down',
        'Crit Damage Up':'Crit Damage Up',
        'Crit Immunity':'Crit Immunity',
        'Damage Immunity':'Damage Immunity',
        'Daze':'Daze',
        'Deathmark':'Deathmark',
        'Defense Down':'Defense Down',
        'Defense Up':'Defense Up',
        'Dispel':'Dispel',
        'DoT':'DoT',
        'Evasion Down':'Evasion Down',
        'Evasion Up':'Evasion Up',
        'Expose':'Expose',
        'Fear':'Fear',
        'Foresight':'Foresight',
        'Frenzy':'Frenzy',
        'Heal':'Heal',
        'Heal Immunity':'Heal Immunity',
        'Health Down':'Health Down',
        'Health Equalization':'Health Equalization',
        'Health Up':'Health Up',
        'Insta Kill':'Insta Kill',
        'Leader: +Counter':'Leader: +Counter',
        'Leader: +Crit Avoid':'Leader: +Crit Avoid',
        'Leader: +Crit Chance':'Leader: +Crit Chance',
        'Leader: +Crit Damage':'Leader: +Crit Damage',
        'Leader: +Defense':'Leader: +Defense',
        'Leader: +Evasion':'Leader: +Evasion',
        'Leader: +Mastery':'Leader: +Mastery',
        'Leader: +Max Health':'Leader: +Max Health',
        'Leader: +Max Protection':'Leader: +Max Protection',
        'Leader: +Offense':'Leader: +Offense',
        'Leader: +Potency':'Leader: +Potency',
        'Leader: +Speed':'Leader: +Speed',
        'Leader: +Tenacity':'Leader: +Tenacity',
        'Leader: -Defense':'Leader: -Defense',
        'Leader: -Potency':'Leader: -Potency',
        'Leader: -Speed':'Leader: -Speed',
        'Leader: Assist':'Leader: Assist',
        'Leader: CD Reduction':'Leader: CD Reduction',
        'Leader: Crit Avoid':'Leader: Crit Avoid',
        'Leader: Protection Up':'Leader: Protection Up',
        'Leader: TM Gain':'Leader: TM Gain',
        'Leader: TMR':'Leader: TMR',
        'Mark':'Mark',
        'Mass Cleanse':'Mass Cleanse',
        'Mass Dispel':'Mass Dispel',
        'Offense Down':'Offense Down',
        'Offense Up':'Offense Up',
        'Passive':'Passive',
        'Perma Death':'Perma Death',
        'Potency Down':'Potency Down',
        'Potency Up':'Potency Up',
        'Pre Taunt':'Pre Taunt',
        'Protection Up':'Protection Up',
        'Revive':'Revive',
        'Shock':'Shock',
        'Speed Down':'Speed Down',
        'Speed Up':'Speed Up',
        'Stagger':'Stagger',
        'Stats Sharing':'Stats Sharing',
        'Stats Stacking':'Stats Stacking',
        'Stealth':'Stealth',
        'Stun':'Stun',
        'Summon':'Summon',
        'TM Gain':'TM Gain',
        'TM Swap':'TM Swap',
        'TMR':'TMR',
        'Target Lock':'Target Lock',
        'Taunt':'Taunt',
        'Tenacity Down':'Tenacity Down',
        'Tenacity Up':'Tenacity Up',
        'Thermal Detonator':'Thermal Detonator',
        'Translation':'Translation',
        'True Damage':'True Damage',
        'Untargetable':'Untargetable',
        'Vulnerable':'Vulnerable',
    },
    {
        'local':'FR-FR',
        # LOCALS
        'EN-US':'English',
        'FR-FR':'Français',
        # COMMANDS
        # Missing arguments
        'missing_arg':'Argument introuvable. Tappez %help pour plus d\'informations.',
        # Local
        'set_local_success':'Nouvelle langue du Bot ',
        'set_local_fail':'Impossible de trouver la langue ',
        # Have
        'have_success':'Personnages avec ',
        'have_fail':'Aucun personnage ne semble interagir avec ',
        # Ability Classes
        'Ability Block':'',
        'Accuracy Down':'',
        'Accuracy Up':'',
        'Advantage':'Avantage',
        'AoE':'',
        'Armor Shred':'',
        'Assist':'',
        'Blind':'Aveuglement',
        'Bonus Attack':'',
        'Bonus Turn':'Tour Bonus',
        'Breach':'Brèche',
        'Buff Immunity':'',
        'Buff Steal':'',
        'Burning':'Brûlure',
        'CD Increase':'',
        'CD Reduction':'',
        'CD Reset':'',
        'Cleanse':'',
        'Confuse':'Confusion',
        'Counter':'Contre-attaque',
        'Crit Chance Down':'',
        'Crit Chance Up':'',
        'Crit Damage Down':'',
        'Crit Damage Up':'',
        'Crit Immunity':'',
        'Damage Immunity':'Immunité aux Dégâts',
        'Daze':'',
        'Deathmark':'Marque de mort',
        'Defense Down':'',
        'Defense Up':'',
        'Dispel':'',
        'DoT':'Dégâts sur la durée',
        'Evasion Down':'',
        'Evasion Up':'',
        'Expose':'',
        'Fear':'Peur',
        'Foresight':'Prévoyance',
        'Frenzy':'Frénésie',
        'Heal':'Soin',
        'Heal Immunity':'Immunité aux soins',
        'Health Down':'',
        'Health Equalization':'Egalisation de vie',
        'Health Up':'',
        'Insta Kill':'Mort Instantannée',
        'Leader: +Counter':'',
        'Leader: +Crit Avoid':'',
        'Leader: +Crit Chance':'',
        'Leader: +Crit Damage':'',
        'Leader: +Defense':'',
        'Leader: +Evasion':'',
        'Leader: +Mastery':'',
        'Leader: +Max Health':'',
        'Leader: +Max Protection':'',
        'Leader: +Offense':'',
        'Leader: +Potency':'',
        'Leader: +Speed':'',
        'Leader: +Tenacity':'',
        'Leader: -Defense':'',
        'Leader: -Potency':'',
        'Leader: -Speed':'',
        'Leader: Assist':'',
        'Leader: CD Reduction':'',
        'Leader: Crit Avoid':'',
        'Leader: Protection Up':'',
        'Leader: TM Gain':'',
        'Leader: TMR':'',
        'Mark':'Marque',
        'Mass Cleanse':'',
        'Mass Dispel':'',
        'Offense Down':'',
        'Offense Up':'',
        'Passive':'Passif',
        'Perma Death':'Mort permanente',
        'Potency Down':'',
        'Potency Up':'',
        'Pre Taunt':'',
        'Protection Up':'',
        'Revive':'',
        'Shock':'Choc',
        'Speed Down':'',
        'Speed Up':'',
        'Stagger':'',
        'Stats Sharing':'',
        'Stats Stacking':'',
        'Stealth':'Camouflage',
        'Stun':'Etourdissement',
        'Summon':'Invocation',
        'TM Gain':'',
        'TM Swap':'',
        'TMR':'',
        'Target Lock':'',
        'Taunt':'Provocation',
        'Tenacity Down':'',
        'Tenacity Up':'',
        'Thermal Detonator':'Détonateur thermique',
        'Translation':'Traduction',
        'True Damage':'',
        'Untargetable':'Inciblable',
        'Vulnerable':'',
    }
]

LOCALS = {
    EN_US:LOCALIZATIONS[0],
    FR_FR:LOCALIZATIONS[1],
}

HELP_LOCAL = {
    # Local
    'local_brief':'Set bot local',
    'local_help':'Set bot localisation.',
    # Who
    'who_brief':'Returns a Character.',
    'who_help':'Returns a Character.',
    # Basic
    'basic_brief':'Returns the Basic Ability of a specified Character.',
    'basic_help':'Returns the Basic Ability of a specified Character.',
    # Kit
    'kit_brief':'Returns all the Abilities of a specified Character.',
    'kit_help':'Returns all the Abilities of a specified Character.',
    # Have
    'have_brief':'Who interacts with a specified Status Effect.',
    'have_help':'Returns a List of Characters that have an interaction with the specified Status Effect.',
    }
