EN_US = 'EN-US'
FR_FR = 'FR-FR'

LOCALIZATIONS = [
    {
        'local':'EN-US',
        # LOCALS
        'EN-US':'English',
        'FR-FR':'Français',
        # COMMANDS
        # Missing arguments
        'missing_wrong_arg':'Missing or Wrong arguments. Check %help for more informations.',
        'embed_too_long':'Too many results to display. Try to narrow down your search parameters.',
        'something_went_wrong':'Something went wrong. I have a bad feeling about this...',
        # Local
        'local_success':'Bot new local set to ',
        'local_fail':'Could not find local ',
        # Have
        'have_success':'Characters with ',
        'have_fail':'No Character seems to interact with ',
        # Basic
        'basic_success':'Basic Attack of ',
        'basic_fail':'No Basic Attack found for the character ',
        # Special
        'special_success':'Special Attack of ',
        'special_fail':'No Special Attack found for the character ',
        'special_incorrect_arg':'Characters only have between 1 and 3 Special Attacks !',
        'less_special_fail':'This character does not have that many Special Attack !',
        # Feat
        'feat_success':'Feats list in ',
        'feat_general':'General feats :\n',
        'feat_fail':'No Feat found.',
        # Effects
        'effects_success':'Here are all ',
        # Status Effects
        'Buffs':'Buffs',
        'Debuffs':'Debuffs',
        'Miscs':'Miscs',
        'Leads':'Leads',
        'Status Effects':{
            'Ability Block':'Ability Block',
            'Accuracy Down':'Accuracy Down',
            'Accuracy Up':'Accuracy Up',
            'Advantage':'Advantage',
            'AoE':'AoE',
            'Armor Shred':'Armor Shred',
            'Assist':'Assist',
            'Blind':'Blind',
            'Bonus Attack':'Bonus Attack',
            'Bonus Turn':'Bonus Turn',
            'Breach':'Breach',
            'Buff Immunity':'Buff Immunity',
            'Buff Steal':'Buff Steal',
            'Burning':'Burning',
            'CD Increase':'CD Increase',
            'CD Reduction':'CD Reduction',
            'CD Reset':'CD Reset',
            'Cleanse':'Cleanse',
            'Confuse':'Confuse',
            'Counter':'Counter',
            'Critical Chance Down':'Critical Chance Down',
            'Critical Chance Up':'Critical Chance Up',
            'Critical Damage Down':'Critical Damage Down',
            'Critical Damage Up':'Critical Damage Up',
            'Critical Hit Immunity':'Critical Hit Immunity',
            'Damage Immunity':'Damage Immunity',
            'Daze':'Daze',
            'Deathmark':'Deathmark',
            'Defense Down':'Defense Down',
            'Defense Up':'Defense Up',
            'Dispel':'Dispel',
            'DoT':'DoT',
            'Evasion Down':'Evasion Down',
            'Evasion Up':'Evasion Up',
            'Expose':'Expose',
            'Fear':'Fear',
            'Foresight':'Foresight',
            'Frenzy':'Frenzy',
            'Heal':'Heal',
            'Heal Immunity':'Heal Immunity',
            'Health Down':'Health Down',
            'Health Equalization':'Health Equalization',
            'Health Up':'Health Up',
            'Health Steal Up':'Health Steal Up',
            'Insta Kill':'Insta Kill',
            'Leader: +Counter':'Leader: +Counter',
            'Leader: +Critical Avoid':'Leader: +Critical Avoid',
            'Leader: +Critical Chance':'Leader: +Critical Chance',
            'Leader: +Critical Damage':'Leader: +Critical Damage',
            'Leader: +Defense':'Leader: +Defense',
            'Leader: +Evasion':'Leader: +Evasion',
            'Leader: +Mastery':'Leader: +Mastery',
            'Leader: +Max Health':'Leader: +Max Health',
            'Leader: +Max Protection':'Leader: +Max Protection',
            'Leader: +Offense':'Leader: +Offense',
            'Leader: +Potency':'Leader: +Potency',
            'Leader: +Speed':'Leader: +Speed',
            'Leader: +Tenacity':'Leader: +Tenacity',
            'Leader: -Defense':'Leader: -Defense',
            'Leader: -Potency':'Leader: -Potency',
            'Leader: -Speed':'Leader: -Speed',
            'Leader: Assist':'Leader: Assist',
            'Leader: CD Reduction':'Leader: CD Reduction',
            'Leader: Critical Avoid':'Leader: Critical Avoid',
            'Leader: Protection Up':'Leader: Protection Up',
            'Leader: TM Gain':'Leader: TM Gain',
            'Leader: TMR':'Leader: TMR',
            'Marked':'Marked',
            'Mass Cleanse':'Mass Cleanse',
            'Mass Dispel':'Mass Dispel',
            'Offense Down':'Offense Down',
            'Offense Up':'Offense Up',
            'Passive':'Passive',
            'Perma Death':'Perma Death',
            'Potency Down':'Potency Down',
            'Potency Up':'Potency Up',
            'Pre Taunt':'Pre Taunt',
            'Protection Over Time':'Protection Over Time',
            'Protection Up':'Protection Up',
            'Retribution':'Retribution',
            'Revive':'Revive',
            'Shock':'Shock',
            'Speed Down':'Speed Down',
            'Speed Up':'Speed Up',
            'Stagger':'Stagger',
            'Stats Sharing':'Stats Sharing',
            'Stats Stacking':'Stats Stacking',
            'Stealth':'Stealth',
            'Stun':'Stun',
            'Summon':'Summon',
            'TM Gain':'TM Gain',
            'TM Swap':'TM Swap',
            'TMR':'TMR',
            'Target Lock':'Target Lock',
            'Taunt':'Taunt',
            'Tenacity Down':'Tenacity Down',
            'Tenacity Up':'Tenacity Up',
            'Thermal Detonator':'Thermal Detonator',
            'Translation':'Translation',
            'True Damage':'True Damage',
            'Untargetable':'Untargetable',
            'Vulnerable':'Vulnerable',
        },
        # CHARACTER ALIASES
        'Characters':{
            'Aayla Secura':['Aayla Secura', 'Aayla'],
            'Admiral Ackbar':['Admiral Ackbar', 'Ackbar'],
            'Admiral Piett':['Admiral Piett', 'Piett'],
            'Ahsoka Tano':['Ahsoka Tano', 'Ahsoka'],
            'Ahsoka Tano (Fulcrum)':['Ahsoka Tano (Fulcrum)', 'Fulcrum'],
            'Amilyn Holdo':['Amilyn Holdo', 'Holdo'],
            'ARC Trooper':['ARC Trooper', 'ARC'],
            'Asajj Ventress':['Asajj Ventress', 'Asajj', 'AV'],
            'Aurra Sing':['Aurra Sing', 'Aurra'],
            'B1 Battle Droid':['B1 Battle Droid', 'B1'],
            'B2 Super Battle Droid':['B2 Super Battle Droid', 'B2'],
            'Barriss Offee':['Barriss Offee', 'Barriss', 'Zarriss'],
            'Bastila Shan':['Bastila Shan', 'Bastilla', 'Basti'],
            'Bastila Shan (Fallen)':['Bastila Shan (Fallen)', 'BSF'],
            'Baze Malbus':['Baze Malbus', 'Baze'],
            'BB-8':['BB-8', 'BB8'],
            'Biggs Darklighter':['Biggs Darklighter', 'Biggs'],
            'Bistan':['Bistan'],
            'Bo-Katan Kryze':['Bo-Katan Kryze', 'Bo-Katan', 'BKK'],
            'Boba Fett':['Boba Fett', 'Boba'],
            'Boba Fett, Scion of Jango': ['Boba Fett, Scion of Jango',
                'Boba Fat', 'Fat Boba', 'Old Boba'],
            'Bodhi Rook':['Bodhi Rook'],
            'Bossk':['Bossk'],
            'C-3PO':['C-3PO', 'C3PO'],
            'Cad Bane':['Cad Bane', 'Cad'],
            'Canderous Ordo':['Canderous Ordo', 'Canderous'],
            'Captain Han Solo':['Captain Han Solo', 'Captain Han', 'Hoth Han',
                'Cholo'],
            'Captain Phasma':['Captain Phasma', 'Phasma'],
            'Cara Dune':['Cara Dune', 'Cara'],
            'Carth Onasi':['Carth Onasi', 'Carth'],
            'Cassian Andor':['Cassian Andor', 'Cassian'],
            'CC-2224 "Cody"':['CC-2224 "Cody"', 'Cody'],
            'Chewbacca':['Chewbacca', 'Chewie'],
            'Chief Chirpa':['Chief Chirpa', 'Chirpa'],
            'Chief Nebit':['Chief Nebit', 'Nebit'],
            'Chirrut Îmwe':['Chirrut Îmwe', 'Chirrut'],
            'Chopper':['Chopper'],
            'Clone Sergeant - Phase I':['Clone Sergeant - Phase I',
                'Clone sgt'],
            'Clone Wars Chewbacca':['Clone Wars Chewbacca', 'CW Chewbacca',
                'CW Chewie', 'CWC'],
            'Colonel Starck':['Colonel Starck', 'Starck'],
            'Commander Ahsoka Tano':['Commander Ahsoka Tano', 'CAT'],
            'Commander Luke Skywalker':['Commander Luke Skywalker', 'CLS'],
            'Coruscant Underworld Police':['Coruscant Underworld Police',
                'CUP'],
            'Count Dooku':['Count Dooku', 'Dooku'],
            'CT-21-0408 "Echo"':['CT-21-0408 "Echo"', 'Echo'],
            'CT-5555 "Fives"':['CT-5555 "Fives"', 'Fives', '5\'s'],
            'CT-7567 "Rex"':['CT-7567 "Rex"', 'Rex'],
            'Dark Trooper':['Dark Trooper', 'DT'],
            'Darth Malak':['Darth Malak', 'Malak'],
            'Darth Maul':['Darth Maul'],
            'Darth Nihilus':['Darth Nihilus', 'Nihilus'],
            'Darth Revan':['Darth Revan', 'DRevan', 'DR'],
            'Darth Sidious':['Darth Sidious', 'Sidious'],
            'Darth Sion':['Darth Sion', 'Sion'],
            'Darth Traya':['Darth Traya', 'Traya'],
            'Darth Talon':['Darth Talon', 'Talon'],
            'Darth Vader':['Darth Vader', 'Vader', 'DV'],
            'Dash Rendar':['Dash Rendar', 'Dash', 'Rendar'],
            'Dathcha':['Dathcha'],
            'Death Trooper':['Death Trooper'],
            'Dengar':['Dengar'],
            'Director Krennic':['Director Krennic', 'Krennic'],
            'Droideka':['Droideka', 'DDK'],
            'Echo':['Echo', 'Bad Batch Echo', 'BB Echo'],
            'Eeth Koth':['Eeth Koth'],
            'Embo':['Embo'],
            'Emperor Palpatine':['Emperor Palpatine', 'Palpatine', 'EP'],
            'Enfys Nest':['Enfys Nest', 'Nest'],
            'Ewok Elder':['Ewok Elder', 'EElder'],
            'Ewok Scout':['Ewok Scout', 'EScout'],
            'Ezra Bridger':['Ezra Bridger', 'Ezra'],
            'Fennec Shand':['Fennec Shand', 'Fennec'],
            'Finn':['Finn'],
            'First Order Executioner':['First Order Executioner', 'FOX'],
            'First Order Officer':['First Order Officer', 'FO Officer', 'FOO'],
            'First Order SF TIE Pilot':['First Order SF TIE Pilot',
                'FO SF TIE'],
            'First Order Stormtrooper':['First Order Stormtrooper',
                'FO Stormtrooper', 'FOST'],
            'First Order TIE Pilot':['First Order TIE Pilot', 'FO TIE'],
            'Gamorrean Guard':['Gamorrean Guard', 'Piggy'],
            'Gar Saxon':['Gar Saxon'],
            'Garazeb "Zeb" Orrelios':['Garazeb "Zeb" Orrelios', 'Zeb'],
            'General Grievous':['General Grievous', 'GG'],
            'General Hux':['General Hux', 'Hux'],
            'General Kenobi':['General Kenobi', 'GK'],
            'General Skywalker':['General Skywalker', 'GAS'],
            'General Veers':['General Veers', 'Veers'],
            'Geonosian Brood Alpha':['Geonosian Brood Alpha', 'GBA'],
            'Geonosian Soldier':['Geonosian Soldier', 'Geo Soldier'],
            'Geonosian Spy':['Geonosian Spy', 'Geo Spy'],
            'Grand Admiral Thrawn':['Grand Admiral Thrawn', 'Thrawn', 'GAT'],
            'Grand Master Yoda':['Grand Master Yoda', 'Yoda', 'GMY'],
            'Grand Moff Tarkin':['Grand Moff Tarkin', 'Tarkin'],
            'Greedo':['Greedo'],
            'Greef Karga':['Greef Karga', 'Greef'],
            'Han Solo':['Han Solo', 'Han'],
            'Hera Syndulla':['Hera Syndulla', 'Hera'],
            'Hermit Yoda':['Hermit Yoda', 'Hyoda', 'Hoda'],
            'HK-47':['HK-47', 'HK'],
            'Hoth Rebel Scout':['Hoth Rebel Scout', 'Hoth Scout'],
            'Hoth Rebel Soldier':['Hoth Rebel Soldier', 'Hoth Soldier'],
            'Hunter':['Hunter'],
            'Iden Versio':['Iden Versio', 'Iden'],
            'IG-100 MagnaGuard':['IG-100 MagnaGuard', 'Magnaguard', 'MG'],
            'IG-11':['IG-11', 'IG11'],
            'IG-86 Sentinel Droid':['IG-86 Sentinel Droid', 'IG86'],
            'IG-88':['IG-88', 'IG88'],
            'Ima-Gun Di':['Ima-Gun Di', 'ImaGunDi'],
            'Imperial Probe Droid':['Imperial Probe Droid', 'IPD'],
            'Imperial Super Commando':['Imperial Super Commando',
                'Imp Commando'],
            'Jango Fett':['Jango Fett', 'Jango'],
            'Jawa':['Jawa'],
            'Jawa Engineer':['Jawa Engineer', 'Jawa Eng'],
            'Jawa Scavenger':['Jawa Scavenger', 'Jawa Scav'],
            'Jedi Consular':['Jedi Consular'],
            'Jedi Knight Anakin':['Jedi Knight Anakin', 'JKA'],
            'Jedi Knight Guardian':['Jedi Knight Guardian', 'Jedi Guardian'],
            'Jedi Knight Luke Skywalker':['Jedi Knight Luke Skywalker', 'JKL'],
            'Jedi Knight Revan':['Jedi Knight Revan', 'Revan', 'JKR'],
            'Jedi Master Kenobi':['Jedi Master Kenobi', 'JMK'],
            'Jedi Master Luke Skywalker':['Jedi Master Luke Skywalker', 'JML'],
            'Jolee Bindo':['Jolee Bindo', 'Jolee'],
            'Juhani':['Juhani'],
            'Jyn Erso':['Jyn Erso'],
            'K-2SO':['K-2SO', 'K2SO'],
            'Kanan Jarrus':['Kanan Jarrus', 'Kanan'],
            'Ki-Adi-Mundi':['Ki-Adi-Mundi', 'KAM'],
            'Kit Fisto':['Kit Fisto'],
            'Kuiil':['Kuiil'],
            'Kylo Ren':['Kylo Ren', 'OG Kylo'],
            'Kyle Katarn':['Kyle Katarn', 'KK'],
            'Kylo Ren (Unmasked)':['Kylo Ren (Unmasked)', 'KRU'],
            'L3-37':['L3-37', 'L3'],
            'Lando Calrissian':['Lando Calrissian', 'Lando'],
            'Lobot':['Lobot'],
            'Logray':['Logray'],
            'Lord Vader':['Lord Vader', 'LV'],
            'Luke Skywalker (Farmboy)':['Luke Skywalker (Farmboy)',
                'Farmboy Luke'],
            'Luminara Unduli':['Luminara Unduli', 'Luminara'],
            'Mace Windu':['Mace Windu', 'Mace', 'Windu', 'Masterin Mace'],
            'Magmatrooper':['Magmatrooper'],
            'Mara Jade, The Emperor\'s Hand':['Mara Jade, The Emperor\'s Hand',
                'Mara Jade'],
            'Maul':['Maul'],
            'Mission Vao':['Mission Vao', 'Mission', 'Vao'],
            'Mob Enforcer':['Mob Enforcer'],
            'Moff Gideon':['Moff Gideon', 'Gideon'],
            'Mon Mothma':['Mon Mothma', 'MM'],
            'Mother Talzin':['Mother Talzin', 'Talzin'],
            'Nightsister Acolyte':['Nightsister Acolyte', 'NS Acolyte',
                'Acolyte'],
            'Nightsister Initiate':['Nightsister Initiate', 'NS Initiate',
                'Initiate'],
            'Nightsister Spirit':['Nightsister Spirit', 'NS Spirit', 'Spirit'],
            'Nightsister Zombie':['Nightsister Zombie', 'NS Zombie', 'Zombie'],
            'Nute Gunray':['Nute Gunray', 'Nute'],
            'Obi-Wan Kenobi (Old Ben)':['Obi-Wan Kenobi (Old Ben)', 'Old Ben'],
            'Omega':['Omega'],
            'Old Daka':['Old Daka', 'Daka'],
            'Padmé Amidala':['Padmé Amidala', 'Padme'],
            'Pao':['Pao'],
            'Paploo':['Paploo'],
            'Plo Koon':['Plo Koon', 'Plo'],
            'Poe Dameron':['Poe Dameron', 'Poe'],
            'Poggle the Lesser':['Poggle the Lesser', 'Poggle'],
            'Princess Leia':['Princess Leia', 'PLeia'],
            'Qi\'ra':['Qi\'ra', 'Qira'],
            'Qui-Gon Jinn':['Qui-Gon Jinn', 'QGJ'],
            'R2-D2':['R2-D2', 'R2D2', 'R2'],
            'Range Trooper':['Range Trooper', 'Range'],
            'Rebel Officer Leia Organa':['Rebel Officer Leia Organa',
                'Hoth Leia', 'Rolo'],
            'Resistance Hero Finn':['Resistance Hero Finn', 'Hero Finn',
                'Bro Finn'],
            'Resistance Hero Poe':['Resistance Hero Poe', 'Hero Poe',
                'Bro Poe'],
            'Resistance Pilot':['Resistance Pilot'],
            'Resistance Trooper':['Resistance Trooper'],
            'Rey':['Rey', 'GL Rey'],
            'Rey (Jedi Training)':['Rey (Jedi Training)', 'JTR', 'RJT'],
            'Rey (Scavenger)':['Rey (Scavenger)', 'Rey Scav', 'Scav Rey'],
            'Rose Tico':['Rose Tico', 'Rose'],
            'Royal Guard':['Royal Guard', 'RG'],
            'Sabine Wren':['Sabine Wren', 'Sabine'],
            'Savage Opress':['Savage Opress', 'Savage'],
            'Scarif Rebel Pathfinder':['Scarif Rebel Pathfinder', 'SRP'],
            'Second Sister':['Second Sister', '2nd Sister'],
            'Shaak Ti':['Shaak Ti', 'Shaak'],
            'Shoretrooper':['Shoretrooper'],
            'Sith Assassin':['Sith Assassin'],
            'Sith Empire Trooper':['Sith Empire Trooper', 'SE Trooper'],
            'Sith Eternal Emperor':['Sith Eternal Emperor', 'SEE'],
            'Sith Marauder':['Sith Marauder', 'Marauder'],
            'Sith Trooper':['Sith Trooper', 'Red Trooper', 'Red'],
            'Snowtrooper':['Snowtrooper', 'Snow'],
            'Starkiller':['Starkiller'],
            'Stormtrooper':['Stormtrooper', 'Gary'],
            'Stormtrooper Han':['Stormtrooper Han', 'ST Han'],
            'Sun Fac':['Sun Fac', 'SF'],
            'Supreme Leader Kylo Ren':['Supreme Leader Kylo Ren', 'SLKR'],
            'T3-M4':['T3-M4', 'T3M4', 'T3'],
            'Talia':['Talia'],
            'Tech':['Tech'],
            'Teebo':['Teebo'],
            'The Armorer':['The Armorer', 'Armorer'],
            'The Mandalorian':['The Mandalorian', 'Mando'],
            'The Mandalorian (Beskar Armor)':['The Mandalorian (Beskar Armor)',
                'Beskar Mando', 'Bando', 'BAM'],
            'Threepio & Chewie':['Threepio & Chewie', '3PO & Chewie',
                'Threepio'],
            'TIE Fighter Pilot':['TIE Fighter Pilot', 'TFP'],
            'Tusken Raider':['Tusken Raider'],
            'Tusken Shaman':['Tusken Shaman'],
            'Ugnaught':['Ugnaught'],
            'URoRRuR\'R\'R':['URoRRuR\'R\'R', 'Uro Ur'],
            'Vandor Chewbacca':['Vandor Chewbacca', 'Vandor', 'Vandor Chewie'],
            'Veteran Smuggler Chewbacca':['Veteran Smuggler Chewbacca',
                'Vet Chewie'],
            'Veteran Smuggler Han Solo':['Veteran Smuggler Han Solo',
                'Vet Han'],
            'Visas Marr':['Visas Marr', 'Visas'],
            'Wampa':['Wampa'],
            'Wat Tambor':['Wat Tambor', 'Wat'],
            'Wedge Antilles':['Wedge Antilles', 'Wedge'],
            'Wicket':['Wicket'],
            'Wrecker':['Wrecker'],
            'Young Han Solo':['Young Han Solo', 'Young Han'],
            'Young Lando Calrissian':['Young Lando Calrissian', 'Young Lando'],
            'Zaalbar':['Zaalbar', 'Big Z'],
            'Zam Wesell':['Zam Wesell', 'Zam'],
        },
    },
    {
        'local':'FR-FR',
        # LOCALS
        'EN-US':'English',
        'FR-FR':'Français',
        # COMMANDS
        # Miscellaneous
        'missing_wrong_arg':'Argument incompatible ou introuvable. Tappez %help pour plus d\'informations.',
        'embed_too_long':'Trop de résultats à afficher. Essayer de réduire vos paramètres de recherche.',
        'something_went_wrong':'Quelque chose ne s\'est pas passé comme prévu.',
        # Local
        'local_success':'Nouvelle langue du Bot ',
        'local_fail':'Impossible de trouver la langue ',
        # Have
        'have_success':'Personnages avec ',
        'have_fail':'Aucun personnage ne semble interagir avec ',
        # Basic
        'basic_success':'Attaque de base de ',
        'basic_fail':'Aucune attaque de base trouvée pour le personnage ',
        # Special
        'special_success':'Attaque Spéciale de ',
        'special_fail':'Aucune Attaque Spéciale trouvée pour le personnage ',
        'special_incorrect_arg':'Les personnages n\'ont qu\'entre 1 et 3 Attaques Spéciales !',
        'less_special_fail':'Ce personnage n\'a pas autant d\'Attaques Spéciales !',
        # Feat
        'feat_success':'Feats du ',
        'feat_general':'Feats généraux :\n',
        'feat_fail':'Aucun Feat trouvé.',
        # Effects
        'effects_success':'Voici tous les Effets de Statut ',
        # Status Effects
        'Buffs':'Positifs',
        'Debuffs':'Négatifs',
        'Miscs':'Divers',
        'Leads':'Chef',
        'Status Effects':{
            'Ability Block':'',
            'Accuracy Down':'',
            'Accuracy Up':'',
            'Advantage':'Avantage',
            'AoE':'',
            'Armor Shred':'',
            'Assist':'',
            'Blind':'Aveuglement',
            'Bonus Attack':'',
            'Bonus Turn':'Tour Bonus',
            'Breach':'Brèche',
            'Buff Immunity':'',
            'Buff Steal':'',
            'Burning':'Brûlure',
            'CD Increase':'',
            'CD Reduction':'',
            'CD Reset':'',
            'Cleanse':'',
            'Confuse':'Confusion',
            'Counter':'Contre-attaque',
            'Critical Chance Down':'',
            'Critical Chance Up':'',
            'Critical Damage Down':'',
            'Critical Damage Up':'',
            'Critical Hit Immunity':'',
            'Damage Immunity':'Immunité aux Dégâts',
            'Daze':'',
            'Deathmark':'Marque de mort',
            'Defense Down':'',
            'Defense Up':'',
            'Dispel':'',
            'DoT':'Dégâts sur la durée',
            'Evasion Down':'',
            'Evasion Up':'',
            'Expose':'',
            'Fear':'Peur',
            'Foresight':'Prévoyance',
            'Frenzy':'Frénésie',
            'Heal':'Soin',
            'Heal Immunity':'Immunité aux soins',
            'Health Down':'',
            'Health Equalization':'Egalisation de vie',
            'Health Up':'',
            'Health Steal Up':'',
            'Insta Kill':'Mort Instantannée',
            'Leader: +Counter':'',
            'Leader: +Critical Avoid':'',
            'Leader: +Critical Chance':'',
            'Leader: +Critical Damage':'',
            'Leader: +Defense':'',
            'Leader: +Evasion':'',
            'Leader: +Mastery':'',
            'Leader: +Max Health':'',
            'Leader: +Max Protection':'',
            'Leader: +Offense':'',
            'Leader: +Potency':'',
            'Leader: +Speed':'',
            'Leader: +Tenacity':'',
            'Leader: -Defense':'',
            'Leader: -Potency':'',
            'Leader: -Speed':'',
            'Leader: Assist':'',
            'Leader: CD Reduction':'',
            'Leader: Critical Avoid':'',
            'Leader: Protection Up':'',
            'Leader: TM Gain':'',
            'Leader: TMR':'',
            'Marked':'Marqué',
            'Mass Cleanse':'',
            'Mass Dispel':'',
            'Offense Down':'',
            'Offense Up':'',
            'Passive':'Passif',
            'Perma Death':'Mort permanente',
            'Potency Down':'',
            'Potency Up':'',
            'Pre Taunt':'',
            'Protection Over Time':'Protection sur la Durée',
            'Protection Up':'',
            'Retribution':'Retribution',
            'Revive':'',
            'Shock':'Choc',
            'Speed Down':'',
            'Speed Up':'',
            'Stagger':'',
            'Stats Sharing':'',
            'Stats Stacking':'',
            'Stealth':'Camouflage',
            'Stun':'Etourdissement',
            'Summon':'Invocation',
            'TM Gain':'',
            'TM Swap':'',
            'TMR':'',
            'Target Lock':'',
            'Taunt':'Provocation',
            'Tenacity Down':'',
            'Tenacity Up':'',
            'Thermal Detonator':'Détonateur thermique',
            'Translation':'Traduction',
            'True Damage':'',
            'Untargetable':'Inciblable',
            'Vulnerable':'',
        },
        # CHARACTER + ALIASES
        'Characters':{
            'Aayla Secura':['Aayla Secura', 'Aayla'],
            'Admiral Ackbar':['Admiral Ackbar', 'Ackbar'],
            'Admiral Piett':['Admiral Piett', 'Piett'],
            'Ahsoka Tano':['Ahsoka Tano', 'Ahsoka'],
            'Ahsoka Tano (Fulcrum)':['Ahsoka Tano (Fulcrum)', 'Fulcrum'],
            'Amilyn Holdo':['Amilyn Holdo', 'Holdo'],
            'ARC Trooper':['ARC Trooper', 'ARC'],
            'Asajj Ventress':['Asajj Ventress', 'Asajj', 'AV'],
            'Aurra Sing':['Aurra Sing', 'Aurra'],
            'B1 Battle Droid':['B1 Battle Droid', 'B1'],
            'B2 Super Battle Droid':['B2 Super Battle Droid', 'B2'],
            'Barriss Offee':['Barriss Offee', 'Barriss', 'Zarriss'],
            'Bastila Shan':['Bastila Shan', 'Bastilla', 'Basti'],
            'Bastila Shan (Fallen)':['Bastila Shan (Fallen)', 'BSF'],
            'Baze Malbus':['Baze Malbus', 'Baze'],
            'BB-8':['BB-8', 'BB8'],
            'Biggs Darklighter':['Biggs Darklighter', 'Biggs'],
            'Bistan':['Bistan'],
            'Bo-Katan Kryze':['Bo-Katan Kryze', 'Bo-Katan', 'BKK'],
            'Boba Fett':['Boba Fett', 'Boba'],
            'Boba Fett, Scion of Jango': ['Boba Fett, Scion of Jango',
                'Boba Fat', 'Fat Boba', 'Old Boba'],
            'Bodhi Rook':['Bodhi Rook'],
            'Bossk':['Bossk'],
            'C-3PO':['C-3PO', 'C3PO'],
            'Cad Bane':['Cad Bane', 'Cad'],
            'Canderous Ordo':['Canderous Ordo', 'Canderous'],
            'Captain Han Solo':['Captain Han Solo', 'Captain Han', 'Hoth Han',
                'Cholo'],
            'Captain Phasma':['Captain Phasma', 'Phasma'],
            'Cara Dune':['Cara Dune', 'Cara'],
            'Carth Onasi':['Carth Onasi', 'Carth'],
            'Cassian Andor':['Cassian Andor', 'Cassian'],
            'CC-2224 "Cody"':['CC-2224 "Cody"', 'Cody'],
            'Chewbacca':['Chewbacca', 'Chewie'],
            'Chief Chirpa':['Chief Chirpa', 'Chirpa'],
            'Chief Nebit':['Chief Nebit', 'Nebit'],
            'Chirrut Îmwe':['Chirrut Îmwe', 'Chirrut'],
            'Chopper':['Chopper'],
            'Clone Sergeant - Phase I':['Clone Sergeant - Phase I',
                'Clone sgt'],
            'Clone Wars Chewbacca':['Clone Wars Chewbacca', 'CW Chewbacca',
                'CW Chewie', 'CWC'],
            'Colonel Starck':['Colonel Starck', 'Starck'],
            'Commander Ahsoka Tano':['Commander Ahsoka Tano', 'CAT'],
            'Commander Luke Skywalker':['Commander Luke Skywalker', 'CLS'],
            'Coruscant Underworld Police':['Coruscant Underworld Police',
                'CUP'],
            'Count Dooku':['Count Dooku', 'Dooku'],
            'CT-21-0408 "Echo"':['CT-21-0408 "Echo"', 'Echo'],
            'CT-5555 "Fives"':['CT-5555 "Fives"', 'Fives', '5\'s'],
            'CT-7567 "Rex"':['CT-7567 "Rex"', 'Rex'],
            'Dark Trooper':['Dark Trooper', 'DT'],
            'Darth Malak':['Darth Malak', 'Malak'],
            'Darth Maul':['Darth Maul'],
            'Darth Nihilus':['Darth Nihilus', 'Nihilus'],
            'Darth Revan':['Darth Revan', 'DRevan', 'DR'],
            'Darth Sidious':['Darth Sidious', 'Sidious'],
            'Darth Sion':['Darth Sion', 'Sion'],
            'Darth Traya':['Darth Traya', 'Traya'],
            'Darth Talon':['Darth Talon', 'Talon'],
            'Darth Vader':['Darth Vader', 'Vader', 'DV'],
            'Dash Rendar':['Dash Rendar', 'Dash', 'Rendar'],
            'Dathcha':['Dathcha'],
            'Death Trooper':['Death Trooper'],
            'Dengar':['Dengar'],
            'Director Krennic':['Director Krennic', 'Krennic'],
            'Droideka':['Droideka', 'DDK'],
            'Echo':['Echo', 'Bad Batch Echo', 'BB Echo'],
            'Eeth Koth':['Eeth Koth'],
            'Embo':['Embo'],
            'Emperor Palpatine':['Emperor Palpatine', 'Palpatine', 'EP'],
            'Enfys Nest':['Enfys Nest', 'Nest'],
            'Ewok Elder':['Ewok Elder', 'EElder'],
            'Ewok Scout':['Ewok Scout', 'EScout'],
            'Ezra Bridger':['Ezra Bridger', 'Ezra'],
            'Fennec Shand':['Fennec Shand', 'Fennec'],
            'Finn':['Finn'],
            'First Order Executioner':['First Order Executioner', 'FOX'],
            'First Order Officer':['First Order Officer', 'FO Officer', 'FOO'],
            'First Order SF TIE Pilot':['First Order SF TIE Pilot',
                'FO SF TIE'],
            'First Order Stormtrooper':['First Order Stormtrooper',
                'FO Stormtrooper', 'FOST'],
            'First Order TIE Pilot':['First Order TIE Pilot', 'FO TIE'],
            'Gamorrean Guard':['Gamorrean Guard', 'Piggy'],
            'Gar Saxon':['Gar Saxon'],
            'Garazeb "Zeb" Orrelios':['Garazeb "Zeb" Orrelios', 'Zeb'],
            'General Grievous':['General Grievous', 'GG'],
            'General Hux':['General Hux', 'Hux'],
            'General Kenobi':['General Kenobi', 'GK'],
            'General Skywalker':['General Skywalker', 'GAS'],
            'General Veers':['General Veers', 'Veers'],
            'Geonosian Brood Alpha':['Geonosian Brood Alpha', 'GBA'],
            'Geonosian Soldier':['Geonosian Soldier', 'Geo Soldier'],
            'Geonosian Spy':['Geonosian Spy', 'Geo Spy'],
            'Grand Admiral Thrawn':['Grand Admiral Thrawn', 'Thrawn', 'GAT'],
            'Grand Master Yoda':['Grand Master Yoda', 'Yoda', 'GMY'],
            'Grand Moff Tarkin':['Grand Moff Tarkin', 'Tarkin'],
            'Greedo':['Greedo'],
            'Greef Karga':['Greef Karga', 'Greef'],
            'Han Solo':['Han Solo', 'Han'],
            'Hera Syndulla':['Hera Syndulla', 'Hera'],
            'Hermit Yoda':['Hermit Yoda', 'Hyoda', 'Hoda'],
            'HK-47':['HK-47', 'HK'],
            'Hoth Rebel Scout':['Hoth Rebel Scout', 'Hoth Scout'],
            'Hoth Rebel Soldier':['Hoth Rebel Soldier', 'Hoth Soldier'],
            'Hunter':['Hunter'],
            'Iden Versio':['Iden Versio', 'Iden'],
            'IG-100 MagnaGuard':['IG-100 MagnaGuard', 'Magnaguard', 'MG'],
            'IG-11':['IG-11', 'IG11'],
            'IG-86 Sentinel Droid':['IG-86 Sentinel Droid', 'IG86'],
            'IG-88':['IG-88', 'IG88'],
            'Ima-Gun Di':['Ima-Gun Di', 'ImaGunDi'],
            'Imperial Probe Droid':['Imperial Probe Droid', 'IPD'],
            'Imperial Super Commando':['Imperial Super Commando',
                'Imp Commando'],
            'Jango Fett':['Jango Fett', 'Jango'],
            'Jawa':['Jawa'],
            'Jawa Engineer':['Jawa Engineer', 'Jawa Eng'],
            'Jawa Scavenger':['Jawa Scavenger', 'Jawa Scav'],
            'Jedi Consular':['Jedi Consular'],
            'Jedi Knight Anakin':['Jedi Knight Anakin', 'JKA'],
            'Jedi Knight Guardian':['Jedi Knight Guardian', 'Jedi Guardian'],
            'Jedi Knight Luke Skywalker':['Jedi Knight Luke Skywalker', 'JKL'],
            'Jedi Knight Revan':['Jedi Knight Revan', 'Revan', 'JKR'],
            'Jedi Master Kenobi':['Jedi Master Kenobi', 'JMK'],
            'Jedi Master Luke Skywalker':['Jedi Master Luke Skywalker', 'JML'],
            'Jolee Bindo':['Jolee Bindo', 'Jolee'],
            'Juhani':['Juhani'],
            'Jyn Erso':['Jyn Erso'],
            'K-2SO':['K-2SO', 'K2SO'],
            'Kanan Jarrus':['Kanan Jarrus', 'Kanan'],
            'Ki-Adi-Mundi':['Ki-Adi-Mundi', 'KAM'],
            'Kit Fisto':['Kit Fisto'],
            'Kuiil':['Kuiil'],
            'Kylo Ren':['Kylo Ren', 'OG Kylo'],
            'Kyle Katarn':['Kyle Katarn', 'KK'],
            'Kylo Ren (Unmasked)':['Kylo Ren (Unmasked)', 'KRU'],
            'L3-37':['L3-37', 'L3'],
            'Lando Calrissian':['Lando Calrissian', 'Lando'],
            'Lobot':['Lobot'],
            'Logray':['Logray'],
            'Lord Vader':['Lord Vader', 'LV'],
            'Luke Skywalker (Farmboy)':['Luke Skywalker (Farmboy)',
                'Farmboy Luke'],
            'Luminara Unduli':['Luminara Unduli', 'Luminara'],
            'Mace Windu':['Mace Windu', 'Mace', 'Windu', 'Masterin Mace'],
            'Magmatrooper':['Magmatrooper'],
            'Mara Jade, The Emperor\'s Hand':['Mara Jade, The Emperor\'s Hand',
                'Mara Jade'],
            'Maul':['Maul'],
            'Mission Vao':['Mission Vao', 'Mission', 'Vao'],
            'Mob Enforcer':['Mob Enforcer'],
            'Moff Gideon':['Moff Gideon', 'Gideon'],
            'Mon Mothma':['Mon Mothma', 'MM'],
            'Mother Talzin':['Mother Talzin', 'Talzin'],
            'Nightsister Acolyte':['Nightsister Acolyte', 'NS Acolyte',
                'Acolyte'],
            'Nightsister Initiate':['Nightsister Initiate', 'NS Initiate',
                'Initiate'],
            'Nightsister Spirit':['Nightsister Spirit', 'NS Spirit', 'Spirit'],
            'Nightsister Zombie':['Nightsister Zombie', 'NS Zombie', 'Zombie'],
            'Nute Gunray':['Nute Gunray', 'Nute'],
            'Obi-Wan Kenobi (Old Ben)':['Obi-Wan Kenobi (Old Ben)', 'Old Ben'],
            'Omega':['Omega'],
            'Old Daka':['Old Daka', 'Daka'],
            'Padmé Amidala':['Padmé Amidala', 'Padme'],
            'Pao':['Pao'],
            'Paploo':['Paploo'],
            'Plo Koon':['Plo Koon', 'Plo'],
            'Poe Dameron':['Poe Dameron', 'Poe'],
            'Poggle the Lesser':['Poggle the Lesser', 'Poggle'],
            'Princess Leia':['Princess Leia', 'PLeia'],
            'Qi\'ra':['Qi\'ra', 'Qira'],
            'Qui-Gon Jinn':['Qui-Gon Jinn', 'QGJ'],
            'R2-D2':['R2-D2', 'R2D2', 'R2'],
            'Range Trooper':['Range Trooper', 'Range'],
            'Rebel Officer Leia Organa':['Rebel Officer Leia Organa',
                'Hoth Leia', 'Rolo'],
            'Resistance Hero Finn':['Resistance Hero Finn', 'Hero Finn',
                'Bro Finn'],
            'Resistance Hero Poe':['Resistance Hero Poe', 'Hero Poe',
                'Bro Poe'],
            'Resistance Pilot':['Resistance Pilot'],
            'Resistance Trooper':['Resistance Trooper'],
            'Rey':['Rey', 'GL Rey'],
            'Rey (Jedi Training)':['Rey (Jedi Training)', 'JTR', 'RJT'],
            'Rey (Scavenger)':['Rey (Scavenger)', 'Rey Scav', 'Scav Rey'],
            'Rose Tico':['Rose Tico', 'Rose'],
            'Royal Guard':['Royal Guard', 'RG'],
            'Sabine Wren':['Sabine Wren', 'Sabine'],
            'Savage Opress':['Savage Opress', 'Savage'],
            'Scarif Rebel Pathfinder':['Scarif Rebel Pathfinder', 'SRP'],
            'Second Sister':['Second Sister', '2nd Sister'],
            'Shaak Ti':['Shaak Ti', 'Shaak'],
            'Shoretrooper':['Shoretrooper'],
            'Sith Assassin':['Sith Assassin'],
            'Sith Empire Trooper':['Sith Empire Trooper', 'SE Trooper'],
            'Sith Eternal Emperor':['Sith Eternal Emperor', 'SEE'],
            'Sith Marauder':['Sith Marauder', 'Marauder'],
            'Sith Trooper':['Sith Trooper', 'Red Trooper', 'Red'],
            'Snowtrooper':['Snowtrooper', 'Snow'],
            'Starkiller':['Starkiller'],
            'Stormtrooper':['Stormtrooper', 'Gary'],
            'Stormtrooper Han':['Stormtrooper Han', 'ST Han'],
            'Sun Fac':['Sun Fac', 'SF'],
            'Supreme Leader Kylo Ren':['Supreme Leader Kylo Ren', 'SLKR'],
            'T3-M4':['T3-M4', 'T3M4', 'T3'],
            'Talia':['Talia'],
            'Tech':['Tech'],
            'Teebo':['Teebo'],
            'The Armorer':['The Armorer', 'Armorer'],
            'The Mandalorian':['The Mandalorian', 'Mando'],
            'The Mandalorian (Beskar Armor)':['The Mandalorian (Beskar Armor)',
                'Beskar Mando', 'Bando', 'BAM'],
            'Threepio & Chewie':['Threepio & Chewie', '3PO & Chewie',
                'Threepio'],
            'TIE Fighter Pilot':['TIE Fighter Pilot', 'TFP'],
            'Tusken Raider':['Tusken Raider'],
            'Tusken Shaman':['Tusken Shaman'],
            'Ugnaught':['Ugnaught'],
            'URoRRuR\'R\'R':['URoRRuR\'R\'R', 'Uro Ur'],
            'Vandor Chewbacca':['Vandor Chewbacca', 'Vandor', 'Vandor Chewie'],
            'Veteran Smuggler Chewbacca':['Veteran Smuggler Chewbacca',
                'Vet Chewie'],
            'Veteran Smuggler Han Solo':['Veteran Smuggler Han Solo',
                'Vet Han'],
            'Visas Marr':['Visas Marr', 'Visas'],
            'Wampa':['Wampa'],
            'Wat Tambor':['Wat Tambor', 'Wat'],
            'Wedge Antilles':['Wedge Antilles', 'Wedge'],
            'Wicket':['Wicket'],
            'Wrecker':['Wrecker'],
            'Young Han Solo':['Young Han Solo', 'Young Han'],
            'Young Lando Calrissian':['Young Lando Calrissian', 'Young Lando'],
            'Zaalbar':['Zaalbar', 'Big Z'],
            'Zam Wesell':['Zam Wesell', 'Zam'],
        },
    },
]

LOCALS = {
    EN_US:LOCALIZATIONS[0],
    FR_FR:LOCALIZATIONS[1],
}

HELP_LOCAL = {
    # Local
    'local_brief':'Set bot local',
    'local_help':'Set bot localisation.',
    # Who
    'who_brief':'Returns a Character.',
    'who_help':'Returns a Character.',
    # Basic
    'basic_brief':'Returns the Basic Ability of a specified Character.',
    'basic_help':'Returns the Basic Ability of a specified Character.',
    # Special
    'special_brief':'Returns the Special Ability of a specified Character.',
    'special_help':'Returns the Special Ability of a specified Character.',
    # Kit
    'kit_brief':'Returns all the Abilities of a specified Character.',
    'kit_help':'Returns all the Abilities of a specified Character.',
    # Have
    'have_brief':'Who interacts with a specified Status Effect.',
    'have_help':'Returns a List of Characters that have an interaction with the specified Status Effect.',
    # Feat
    'feat_brief':'Get some tips to achieve the Conquest Feats.',
    'feat_help':'Get some tips to achieve the Conquest Feats.',
    # Effects
    'effects_brief':'Lists all Status Effects.',
    'effects_help':'Lists all Status Effects.',
    }
